services:
  mysql:
    image: mysql:8.0
    networks:
      - app-network
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mydb
    volumes:
      - mysql_data:/var/lib/docker_mysql
    ports:
      - "3307:3306"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    networks:
      - app-network
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    networks:
      - app-network
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - ./api/config/mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=mark3

  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    networks:
      - app-network
    ports:
      - "5673:5672"   # AMQP协议端口
      - "15673:15672" # 管理界面端口
    volumes:
      - rabbitmq_data:/var/lib/docker_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  mark_table_server:
    image: marktable/mark_table_server:${WEB_APP_VERSION}
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8075:8080"
    volumes:
      - ./documents:/app/documents  # 挂载文档目录
      - ./uploads:/app/uploads
      - ./tmp:/app/tmp
    environment:
      - LIBREOFFICE_PATH=/usr/bin/libreoffice
      - UPLOAD_DIR=/app/uploads
      - TMP_DIR=/app/tmp
    depends_on:
      - mysql
      - redis
      - mongodb
      - rabbitmq
    networks:
      - app-network
    restart: unless-stopped

  mark_table_client:
    image: marktable/mark_table_client:${WEB_APP_VERSION}
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - NODE_ENV=out
    networks:
      - app-network
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=prod
      - VUE_APP_MARKTABLE_SERVER_PATH=http://localhost/api/ # 添加环境变量
      - VUE_APP_DASHBOARD_SERVER_PATH=http://localhost/api/ # 添加环境变量
      - VUE_APP_DOWNLOAD_FILE_SERVER_PATH=http://localhost:8081/ # 添加环境变量
    volumes:
      - ./uploads:/www/mark3_server_upload
    depends_on:
      - mark_table_server


networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  mongo_data:
  rabbitmq_data:
